// eagool-spa/src/components/HomePage.vue
<script setup lang="ts">
import { inject } from 'vue';
import { AuthService } from '../services/auth.service';
import router from '../router';
import NavBar from './utils/NavBar.vue';
import { UserRole } from '../models/user';

const authService = inject('auth-service') as AuthService;

if (authService.isAuthorized()) {
  const role = authService.getUser().role;
  if (role === UserRole.admin) {
    console.log('redirecting to admin panel!');
    router.push({ name: 'admin-panel' });
  } else if (role === UserRole.tutor) {
    console.log('redirecting to tutor home page!');
    router.push({ name: 'tutor-panel' });
  } else {
    console.log('TODO: implement student pages');
  }
}
</script>

<template>
  <NavBar :routes="[]" :auth="{ name: 'Войти', path: '/auth' }" />

  <div class="container mt-3">
    <h1>EAGOOL</h1>
    <h3>
      Приложение для контроля выполнения домашних заданий по английскому языку
    </h3>
  </div>
</template>

// eagool-spa/src/app/pages/home-page/home-page.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthService } from 'src/app/services/auth.service';
import { UserRole } from 'src/app/models/user.model';

@Component({
  selector: 'app-home-page',
  templateUrl: './home-page.component.html',
  styleUrls: ['./home-page.component.css'],
})
export class HomePageComponent implements OnInit {
  isLoggedIn: boolean = false;
  isAdmin: boolean = false;
  isTutor: boolean = false;
  isStudent: boolean = false;

  constructor(private authService: AuthService) {
    this.isLoggedIn = authService.isLoggedIn();
    if (this.isLoggedIn) {
      switch (authService.getThisUser().role) {
        case UserRole.ADMIN:
          this.isAdmin = true;
          break;
        case UserRole.TUTOR:
          this.isTutor = true;
          break;
        case UserRole.STUDENT:
          this.isStudent = true;
          break;
      }
    }
  }

  ngOnInit() {}
}

<div>
  <app-header></app-header>

  <div *ngIf="!isLoggedIn">
    <p>
      Eagool - система контроля выполнения домашних заданий по английскому языку
    </p>
  </div>

  <app-admin-home *ngIf="isAdmin"></app-admin-home>

  <app-footer></app-footer>
</div>
